sonar.coverage.exclusions=tests/**
sonar.exclusions=tests/**
sonar.projectKey=Home-Office-Digital:core-cloud-terraform-modules:modules-products-static-site
sonar.projectName=core-cloud-terraform-modules/modules/products/static-site
