sonar.coverage.exclusions=tests/**
sonar.exclusions=tests/**
sonar.projectKey=Home-Office-Digital:core-cloud-terraform-modules:modules-aws-networking-ctn-connect-attachment
sonar.projectName=core-cloud-terraform-modules/modules/aws/networking/ctn-connect-attachment
