sonar.coverage.exclusions=tests/**
sonar.exclusions=tests/**
sonar.projectKey=Home-Office-Digital:core-cloud-terraform-modules:modules-aws-group_user_memberships
sonar.projectName=core-cloud-terraform-modules/modules/aws/group_user_memberships
