sonar.coverage.exclusions=tests/**
sonar.exclusions=tests/**
sonar.projectKey=Home-Office-Digital:core-cloud-terraform-modules:modules-aws-cost_usage_reports
sonar.projectName=core-cloud-terraform-modules/modules/aws/cost_usage_reports
