sonar.coverage.exclusions=tests/**
sonar.exclusions=tests/**
sonar.projectKey=Home-Office-Digital:core-cloud-terraform-modules:modules-aws-logging-cw-logs-destination
sonar.projectName=core-cloud-terraform-modules/modules/aws/logging/cw-logs-destination
